# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x15quantum_visualization\")\n\x06Vector\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"p\n\nTrajectory\x12\n\n\x02id\x18\x01 \x01(\t\x12-\n\x06points\x18\x02 \x03(\x0b\x32\x1d.quantum_visualization.Vector\x12\x13\n\x0b\x66ull_params\x18\x03 \x03(\x01\x12\x12\n\nloss_value\x18\x04 \x01(\x01\"?\n\tLandscape\x12\x10\n\x08x_coords\x18\x01 \x03(\x01\x12\x10\n\x08y_coords\x18\x02 \x03(\x01\x12\x0e\n\x06values\x18\x03 \x03(\x01\"\x80\x01\n\x07UIEvent\x12\x12\n\ncontrol_id\x18\x01 \x01(\t\x12\x15\n\x0b\x66loat_value\x18\x02 \x01(\x01H\x00\x12\x13\n\tint_value\x18\x03 \x01(\x05H\x00\x12\x16\n\x0cstring_value\x18\x04 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x05 \x01(\x08H\x00\x42\x07\n\x05value\"F\n\x10SaveConfirmation\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"$\n\x11ResetConfirmation\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x9d\x02\n\x0eRealtimeUpdate\x12\x35\n\tlandscape\x18\x01 \x01(\x0b\x32 .quantum_visualization.LandscapeH\x00\x12\x37\n\ntrajectory\x18\x02 \x01(\x0b\x32!.quantum_visualization.TrajectoryH\x00\x12\x44\n\x11save_confirmation\x18\x03 \x01(\x0b\x32\'.quantum_visualization.SaveConfirmationH\x00\x12\x46\n\x12reset_confirmation\x18\x04 \x01(\x0b\x32(.quantum_visualization.ResetConfirmationH\x00\x42\r\n\x0bupdate_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTOR']._serialized_start=41
  _globals['_VECTOR']._serialized_end=82
  _globals['_TRAJECTORY']._serialized_start=84
  _globals['_TRAJECTORY']._serialized_end=196
  _globals['_LANDSCAPE']._serialized_start=198
  _globals['_LANDSCAPE']._serialized_end=261
  _globals['_UIEVENT']._serialized_start=264
  _globals['_UIEVENT']._serialized_end=392
  _globals['_SAVECONFIRMATION']._serialized_start=394
  _globals['_SAVECONFIRMATION']._serialized_end=464
  _globals['_RESETCONFIRMATION']._serialized_start=466
  _globals['_RESETCONFIRMATION']._serialized_end=502
  _globals['_REALTIMEUPDATE']._serialized_start=505
  _globals['_REALTIMEUPDATE']._serialized_end=790
# @@protoc_insertion_point(module_scope)
