steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/processor/processor:latest'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/processor/processor:latest'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'processor'
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/processor/processor:latest'
  - '--region'
  - 'us-central1'
  - '--cpu=2'
  - '--memory=4Gi'
  - '--service-account=pipeline-sa@$PROJECT_ID.iam.gserviceaccount.com'
  - '--timeout=900'
  - '--max-instances=5'
  - '--ingress=all'
  - '--platform=managed'
  - '--allow-unauthenticated'

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/processor/processor:latest'
